//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAspMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabRoom
    {
        public LabRoom()
        {
            this.Queues = new HashSet<Queue>();
        }
    
        public long LabRoomId { get; set; }
        public string Subject { get; set; }
        public System.DateTime Date { get; set; }
        public string Task { get; set; }
        public int MaxPeopleInGroup { get; set; }
    
        public virtual ICollection<Queue> Queues { get; set; }
    }
}
