//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAspMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueGroup
    {
        public int QueueGroupId { get; set; }
        public long StudentId { get; set; }
        public long QueueId { get; set; }
    
        public virtual Queue Queue { get; set; }
        public virtual Student Student { get; set; }
    }
}
