//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAspMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public Queue()
        {
            this.QueueGroups = new HashSet<QueueGroup>();
        }
    
        public long QueueId { get; set; }
        public long LabRoomId { get; set; }
    
        public virtual LabRoom LabRoom { get; set; }
        public virtual ICollection<QueueGroup> QueueGroups { get; set; }
    }
}
